### ISSUE TITLE
derivation of response term for conditional topic distribution

### ISSUE THREAD

**Issue by mkarikom** [ywwbill/SupervisedLDA#1]
On line 150-154 of SLDA.java, the following change to the conditional topic distribution:

> if (type==TRAIN && labelStatuses[doc])
> {
>   score+=-MathUtil.sqr(labels[doc]-weight-eta[topic]/corpus.get(doc).docLength())/
>       (2.0*MathUtil.sqr(param.sigma));
> }

Can you briefly explain where this comes from?  Also curious whether this is the only published implementation of collapsed Gibbs EM sLDA?  Thanks!

**Comment by ywwbill** [comment]
I derived the equations on my own, following the vanilla LDA's Gibbs sampling equation derivation in [Parameter Estimation for Text Analysis](http://www.arbylon.net/publications/text-est.pdf).

I do not think this is the only implementation of collapsed Gibbs sLDA. [This repo](https://github.com/vietansegan/segan) has another version of implementation.

**Comment by mkarikom** [comment]
Thanks for your reply!  I will check out the references.
